spring:
  application:
    name: whatsapp-backend
server:
  port: ${PORT:8082}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# Firebase Configuration
firebase:
  config-path: ${FIREBASE_CONFIG_PATH:src/main/resources/firebase-service-account.json}

# WhatsApp API Configuration
whatsapp:
  token: ${WHATSAPP_ACCESS_TOKEN:your_access_token_here}
  api-url: ${WHATSAPP_API_URL:https://graph.facebook.com/v19.0}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID:your_phone_number_id_here}
  webhook-verify-token: ${WHATSAPP_WEBHOOK_VERIFY_TOKEN:your_webhook_verify_token_here}
  app-id: ${WHATSAPP_APP_ID:your_app_id_here}
  app-secret: ${WHATSAPP_APP_SECRET:your_app_secret_here}

# Springdoc OpenAPI (Swagger) Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    com.jaruratcare.whatsapp: DEBUG
    org.springframework.web: INFO 