spring:
  application:
    name: whatsapp-backend
server:
  port: 8081

# Firebase Configuration
firebase:
  config-path: ${FIREBASE_CONFIG_PATH:src/main/resources/firebase-service-account.json}

# WhatsApp API Configuration
whatsapp:
  token: "dummy_token"
  api-url: "https://graph.facebook.com/v19.0"
  phone-number-id: "dummy_phone_number_id"

# Springdoc OpenAPI (Swagger) Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    com.jaruratcare.whatsapp: DEBUG
    org.springframework.web: INFO 